// Example songs to create a playlist
export const songs: Array<string> = [
  'Más de lo que aposté Aitana;Morat',
  'Hawai Maluma',
  'Break my heart Dua Lipa',
  'In your eyes The Weeknd',
  'A un paso de la luna Ana Mena;Rocco Hunt',
  "Let's love David Guetta;Sia",
  'Jerusalema Master KG;Nomcebo',
  'Mi religión Nil Moliner',
  'Savage love (Laxed - Siren beat) Jason Derülo;Jawsh 685',
  'Dynamite BTS',
  'Si hubieras querido Pablo Alborán',
  'Mood 24kGoldn;Iann Dior',
  'Kings & queens Ava Max',
  'Santería Danna Paola;Denise Rosenthal;Lola Índigo',
  'Tattoo Camilo;Rauw Alejandro',
  'Capítulos Dvicio',
  'Head & heart Joel Corry;MNEK',
  'Watermelon sugar Harry Styles',
  'Diamonds Sam Smith',
  'Djadja Aya Nakamura;Maluma',
  'Midnight sky Miley Cyrus',
  'Un día (One day) Bad Bunny;Dua Lipa;J Balvin;Tainy',
  'A dónde van Álvaro Díaz;Sebastián Yatra',
  'Del mar Doja Cat;Ozuna;Sia',
  'Si tú la quieres Aitana;David Bisbal',
  'Hoy Antonio Orozco',
  'Mundo imperfecto Sidecars',
  'Los huesos Dani Martín;Juanes',
  'Levitating Dua Lipa',
  'Favorito Camilo',
  'Blinding lights The Weeknd',
  'Y vuelo Vanesa Martín',
  'Tusa Karol G;Nicki Minaj',
  'La noche suena Dani Fernández;David Otero',
  'Se iluminaba Fred de Palma;Ana Mena',
  'Portales Dani Martín',
  'Sueño Beret;Pablo Alborán',
  'Pa toda la vida Don Patricio;Mozart La Para',
  'Physical Dua Lipa',
  'Mariposa Pablo López',
]

export default songs
